/*	Archivo:	delay_server.c
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "delay.h"
/* agregado v */
#include<unistd.h>	
/* agregado ^ */

void *
demora_1_svc(struct svc_req *rqstp)
{
	static char * result;
	/* agregado v */
	sleep(10);	
	/* agregado ^ */
	return (void *) &result;
}
/*Fin del archivo:	delay_server.c */
