/*	Archivo:	delay_client.c
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "delay.h"

void
delay_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, DELAY, VDELAY, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = demora_1(clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	delay_1 (host);
exit (0);
}
/*	Archivo:	delay_client.c */
